verb1 = input("Enter a verb: ")
singular_noun1 = input("Enter a singular_noun: ")
verb2 = input("Enter another verb: ")
adjective2 = input("Enter another adjective: ")
adjective3 = input("Enter another adjective: ")
singular_noun2 = input("Enter a singular_noun: ")
name_of_your_one_body_part = input("Now enter the name of your one body part:")
verb3 = input("Enter another verb: ")
adjective4 = input("Enter another adjective: ")

print(f"I used to {verb1} all day long.")
print(f"Oneday I saw a {singular_noun1} in the park.")
print(f"I tried to {verb2} that with my {adjective2} hand.")
print(f"Then I saw you eating a {singular_noun2} with your {name_of_your_one_body_part}. ")
print(f"That {verb3} me to feel {adjective4}.")